name: $(VersionMajor).$(VersionMinor).$(VersionBuild).$(VersionRevision)

trigger:
  branches:
    include:
    - source
  paths:
    include:
    - src

pool:
#  vmImage: windows-latest
  demands: InnoSetup

variables:
- name: ApplicationName
  value: $(Build.DefinitionName)
- name: SolutionFile
  value: 'src/Server-Managers.sln'
- name: ProjectFile
  value: 'src/$(ApplicationName)/$(ApplicationName).csproj'

stages:
- template: azure-pipelines-build.yml@self
  parameters:
    ApplicationName: $(ApplicationName)
    SolutionFile: $(SolutionFile)
    ProjectFile: $(ProjectFile)

- stage: deployBeta
  displayName: Beta
  lockBehavior: runLatest
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/source'))
  dependsOn: 
  - build

  jobs:
  - deployment: deployBeta
    displayName: Deploy Beta
    environment: github-servermanager-beta

- stage: deployRelease
  displayName: Production
  lockBehavior: runLatest
  condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/source'))
  dependsOn: 
  - deployBeta

  jobs:
  - deployment: deployRelease
    displayName: Deploy Production
    environment: github-servermanager-release
