name: $(VersionMajor).$(VersionMinor).$(VersionBuild).$(VersionRevision)

trigger:
  branches:
    include:
    - source
  paths:
    include:
    - src

variables:
  - name: solutionFile
    value: 'src/Server-Managers.sln'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet 4.4.1'
  inputs:
    versionSpec: '4.4.1'

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '$(solutionFile)'

- task: PowerShell@2
  displayName: 'Apply Semantic Versioning to Assemblies'
  inputs:
    targetType: filePath
    filePath: './.azure/scripts/ApplySemanticVersioningToAssemblies.ps1'
    arguments: "-applicationName $(ApplicationName) -pathToSearch './src' -buildNumber $()"
    pwsh: true
