steps:
- task: PowerShell@2
  displayName: Create AgentCapabilities Environment Variables
  env:
    SYSTEM_ACCESSTOKEN: $(System.AccessToken)
  inputs:
    targetType: filePath
    filePath: './.azure/scripts/CreateAgentCapabilitiesEnvironmentVariables.ps1'
    arguments: "-CollectionUri '$(System.CollectionUri)' -AgentId '$(Agent.Id)' -AgentName '$(Agent.Name)' -AccessToken '$(System.AccessToken)' -DebugMode $(System.Debug)"
    pwsh: true
