steps:
- task: PowerShell@2
  displayName: Output Environment Variables
  condition: contains(variables['system.debug'], 'true')
  inputs:
    targetType: inline
    script: '(gci env:*).GetEnumerator() | Sort-Object Name | Out-String'
    pwsh: true
